version: '3'
services:
  redash:
    build:
      context: ./redash
    ports:
      - "5000:5000"
    environment:
      REDASH_DATABASE_URL: "postgresql://postgres:password@postgres:5432/postgres"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_MONGODB_URL: "mongodb://monitorUser:monitorPassword@172.20.0.4:27017/admin"
    depends_on:
      - redis
      - postgres
    networks:
      - redash-network
      - kafka-network  # Connect to the external Kafka network to access MongoDB

  redash_worker:
    image: redash/redash:latest
    command: worker
    environment:
      REDASH_DATABASE_URL: "postgresql://postgres:password@postgres:5432/postgres"
      REDASH_REDIS_URL: "redis://redis:6379/0"  # Update this to point to the Redis container
      QUEUES: "queries,scheduled_queries,celery"
      WORKERS_COUNT: 2  # Adjust this number based on your needs
    depends_on:
      - redash
      - redis
    networks:
      - redash-network
      - kafka-network
    restart: always

  redis:
    image: redis:6.0-alpine
    ports:
      - "6379:6379"
    networks:
      - redash-network

  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - redash-network

networks:
  redash-network:
    driver: bridge
  kafka-network:
    external: true  # Use the external Kafka network where MongoDB resides
